Vagrant.configure("2") do |config|
  config.vm.define :demo do |node|
        node.vm.box = "precise64"
#        node.vm.box = "trusty64"
        node.vm.network :private_network, ip: "10.255.0.2", netmask: "255.255.0.0"
	node.vm.provision "chef_solo" do |chef|
		chef.cookbooks_path = ["cookbooks", "cookbooks"]
		chef.add_recipe "aptmirror"
		chef.add_recipe "apache"
		chef.add_recipe "php"
		chef.json = {
			"aptmirror" => {
				"server" => "192.168.28.102"
			}
                }
	end
  end
end
